package auth

const (
	CREATE_PREFERENCE uint64 = 1 << iota
	UPDATE_PREFERENCE
	DELETE_PREFERENCE

	CREATE_BLOQ
	UPDATE_BLOQ
	DELETE_BLOQ

	PREFERENCE_MANAGER = CREATE_PREFERENCE | UPDATE_PREFERENCE | DELETE_PREFERENCE

    DEFAULT_PERMISSIONS = CREATE_BLOQ | UPDATE_BLOQ
)
