package auth

import "github.com/bloqs-sites/bloqsenjin/pkg/auth"

const (
	CREATE_PREFERENCE auth.Permissions = 1 << iota
	UPDATE_PREFERENCE
	DELETE_PREFERENCE

	CREATE_BLOQ
	UPDATE_BLOQ
	DELETE_BLOQ

	PREFERENCE_MANAGER = CREATE_PREFERENCE | UPDATE_PREFERENCE | DELETE_PREFERENCE

    DEFAULT_PERMISSIONS = CREATE_BLOQ | UPDATE_BLOQ
)
